WITH CTE_AUX_ASESOR AS (
    SELECT
        T_PRE.PERIODO AS Periodo,
        CASE 
            WHEN T_ANA.ID_AGE = '98' AND RIGHT(RTRIM(T_ANA.ID_USER), 1) = '6' THEN '06'
            WHEN T_ANA.ID_AGE = '98' AND RIGHT(RTRIM(T_ANA.ID_USER), 1) = '7' THEN '07'
            ELSE T_ANA.ID_AGE 
        END AS IdSAgencia,
        T_ANA.ID_USER AS IdSAsesor,
        T_PER.RAZON AS AsesorNombresApellidos,
        T_CAR.DESCRIP AS Cargo
    FROM PREEC T_PRE
    INNER JOIN SEGURIDAD.DBO.ANAREC T_ANA ON T_ANA.ID_ANAREC = T_PRE.ID_ANA AND T_ANA.FLAG_ANAREC = 'A'
    INNER JOIN SEGURIDAD.dbo.USUARIOS T_USU ON T_USU.ID_USER = T_ANA.ID_USER
    INNER JOIN SEGURIDAD.dbo.GRUPOUSER T_GRU ON T_GRU.ID_GRUPO = T_USU.ID_GRUPO AND T_GRU.NOM_GRUPO = 'CREDITOS'
    INNER JOIN SEGURIDAD.dbo.PERSONAL T_PER ON T_PER.DNI = T_USU.DNI
    INNER JOIN SEGURIDAD.dbo.TCARGO_USER T_CAR ON T_CAR.ID_CARGO = T_PER.ID_CARGO
    WHERE T_PRE.PERIODO = :periodo AND T_PRE.SALDO_PRES > 0
    AND T_USU.ID_USER NOT IN ('PRECASTIGO', 'RJULI6', 'RJULIACA', 'RLIMA7', 'RQUILLA3', 'RSICUA4', 'LHR5', 'HTEJ5', 'TKPN5', 'GHVJ5', 'OTA5', 'SDHF5', 'CMN5', 'HQND5')
)
SELECT DISTINCT T.Periodo, T.IdSAgencia, T.IdSAsesor, T.AsesorNombresApellidos, T.Cargo, 30 AS ColocacionNumMeta
FROM CTE_AUX_ASESOR T;