WITH CTE_ASESOR AS (
    SELECT DISTINCT 
        T_ANA.ID_USER AS IdSAsesor, 
        CASE
            WHEN T_ANA.ID_AGE = '98' THEN
                CASE WHEN RIGHT(RTRIM(T_ANA.ID_USER), 1) = '6' THEN '06' WHEN RIGHT(RTRIM(T_ANA.ID_USER), 1) = '7' THEN '07' END
            WHEN T_ANA.ID_AGE = '01' THEN
                CASE WHEN RIGHT(RTRIM(T_ANA.ID_USER), 1) <> '9' THEN '01' WHEN RIGHT(RTRIM(T_ANA.ID_USER), 1) = '9' THEN '09' END
            ELSE T_ANA.ID_AGE
        END AS IdSAgencia
    FROM PREEC T_PRE
    INNER JOIN SEGURIDAD.DBO.ANAREC T_ANA ON T_ANA.ID_ANAREC = T_PRE.ID_ANA AND T_ANA.FLAG_ANAREC = 'A'
    WHERE T_PRE.PERIODO = :periodo AND T_PRE.SALDO_PRES > 0
),
CTE_CARTERA_MORAS AS (
    SELECT T_PRE.PERIODO, T_ANA.ID_USER AS IdSAsesor,
        SUM(T_PRE.SALDO_PRES) AS Cartera,
        SUM(CASE WHEN T_PRE.DIAS_REALES >= 9 THEN T_PRE.SALDO_PRES ELSE 0 END) AS Mora9,
        SUM(CASE WHEN T_PRE.DIAS_REALES >= 31 THEN T_PRE.SALDO_PRES ELSE 0 END) AS Mora31,
        SUM(CASE WHEN T_PRE.DIAS_REALES >= 151 THEN T_PRE.SALDO_PRES ELSE 0 END) AS Mora150
    FROM PREEC T_PRE
    INNER JOIN SEGURIDAD.DBO.ANAREC T_ANA ON T_ANA.ID_ANAREC = T_PRE.ID_ANA AND T_ANA.FLAG_ANAREC = 'A'
    WHERE T_PRE.PERIODO = :periodo GROUP BY T_PRE.PERIODO, T_ANA.ID_USER
),
CTE_DURACION AS (
    SELECT T_PRE.PERIODO, T_ANA.ID_USER AS IdSAsesor, SUM(T_DED.CAPITAL) AS Varios
    FROM PRESTAMO T_PTM
    INNER JOIN PREEC T_PRE ON T_PRE.CUENTA = T_PTM.CUENTA AND T_PRE.OTORGA = T_PTM.OTORGA AND T_PRE.PAGARE = T_PTM.PAGARE AND T_PRE.PERIODO = :periodo
    INNER JOIN SEGURIDAD.dbo.ANAREC T_ANA ON T_ANA.ID_ANAREC = T_PRE.ID_ANA AND T_ANA.FLAG_ANAREC = 'A'
    INNER JOIN PRE_DEDUCESOLI T_DED ON T_PTM.PAGARE = T_DED.NRO_SOL AND GLOSA = 'Cursos-Capacitación'
    WHERE T_PTM.TIPO_PROD <> '52' AND FORMAT(T_PTM.OTORGA, 'yyyyMM') = :periodo GROUP BY T_PRE.PERIODO, T_ANA.ID_USER
),
CTE_TEA AS (
    SELECT T_PRE.PERIODO, T_ANA.ID_USER AS IdSAsesor, SUM(T_PTM.MONTO_PRESTAMO * T_PTM.TEA_INTERES) / NULLIF(SUM(T_PTM.MONTO_PRESTAMO), 0) AS TEA
    FROM PRESTAMO T_PTM
    INNER JOIN PREEC T_PRE ON T_PRE.CUENTA = T_PTM.CUENTA AND T_PRE.OTORGA = T_PTM.OTORGA AND T_PRE.PAGARE = T_PTM.PAGARE AND T_PRE.PERIODO = :periodo
    INNER JOIN SEGURIDAD.dbo.ANAREC T_ANA ON T_ANA.ID_ANAREC = T_PRE.ID_ANA AND T_ANA.FLAG_ANAREC = 'A'
    WHERE T_PTM.TIPO_PROD <> '52' AND FORMAT(T_PTM.OTORGA, 'yyyyMM') = :periodo GROUP BY T_PRE.PERIODO, T_ANA.ID_USER
),
CTE_SOCIOS AS (
    SELECT T_PRE.PERIODO, T_ANA.ID_USER AS IdSAsesor, COUNT(DISTINCT T_PRE.CUENTA) AS NroSocios
    FROM PREEC T_PRE
    INNER JOIN SEGURIDAD.DBO.ANAREC T_ANA ON T_ANA.ID_ANAREC = T_PRE.ID_ANA AND T_ANA.FLAG_ANAREC = 'A'
    WHERE T_PRE.PERIODO = :periodo AND T_PRE.SALDO_PRES > 0 GROUP BY T_PRE.PERIODO, T_ANA.ID_USER
),
-- 🌟 NUEVA CTE: Extrae el conteo de socios del periodo inmediatamente anterior
CTE_SOCIOS_ANTERIOR AS (
    SELECT T_ANA.ID_USER AS IdSAsesor, COUNT(DISTINCT T_PRE.CUENTA) AS NroSociosAnterior
    FROM PREEC T_PRE
    INNER JOIN SEGURIDAD.DBO.ANAREC T_ANA ON T_ANA.ID_ANAREC = T_PRE.ID_ANA AND T_ANA.FLAG_ANAREC = 'A'
    WHERE T_PRE.PERIODO = CONVERT(VARCHAR(6), DATEADD(MONTH, -1, CAST(:periodo + '01' AS DATE)), 112)
      AND T_PRE.SALDO_PRES > 0 
    GROUP BY T_ANA.ID_USER
)
SELECT 
    T_CAR.PERIODO AS Periodo, 
    T_ASE.IdSAgencia, 
    T_CAR.IdSAsesor, 
    T_CAR.Cartera, 
    T_CAR.Mora9, 
    T_CAR.Mora31, 
    T_CAR.Mora150,
    ISNULL(T_DUR.Varios, 0) AS Varios, 
    ISNULL(T_TEA.TEA, 0) AS TEA, 
    ISNULL(T_SOC.NroSocios, 0) AS NroSocios,
    ISNULL(T_ANT.NroSociosAnterior, 0) AS NroSociosAnterior -- 🌟 Mapeo de la columna faltante hacia la base local
FROM CTE_CARTERA_MORAS T_CAR
INNER JOIN CTE_ASESOR T_ASE ON T_ASE.IdSAsesor = T_CAR.IdSAsesor
LEFT JOIN CTE_DURACION T_DUR ON T_DUR.IdSAsesor = T_CAR.IdSAsesor
LEFT JOIN CTE_TEA T_TEA ON T_TEA.IdSAsesor = T_CAR.IdSAsesor
LEFT JOIN CTE_SOCIOS T_SOC ON T_SOC.IdSAsesor = T_CAR.IdSAsesor
LEFT JOIN CTE_SOCIOS_ANTERIOR T_ANT ON T_ANT.IdSAsesor = T_CAR.IdSAsesor;